# Notes:
# 1> Open Postman App,  select 'POST'  
#     https://api.github.com/repos/{owner}/{repo}/dispatches   
#     Example: https://api.github.com/repos/mdfareed2001/example-event-dispatcher-workflows/dispatches
# 2> Authorization tab:
#      Type:  'Basic Auth'  
#         Username : <Blank>
#         Password: [Generate Personal Access Token from GitHub > Settings > Developer Settings  and paste here.]
# 3> Headers  tab:
#     Accept:    application/vnd.github.everest-preview+json
#     Content-Type:   application/json
# 4> Body tab:  select 'raw' and 'JSON' from dropdown.
# { 
# 	"event_type": "run-ping-allinone",
# 	"client_payload": {
# 		"command": "ping"
# 	}
# }
# 5> 'Send'   To verify sent, check response 'Status: 204 No Content'
# 6> Verify Workflow is triggered under Actions tab in GitHub Actions.

name: All-In-One
env:
  REPO_OWNER: mdfareed2001
  REPO_NAME: example-event-dispatcher-workflows
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  repository_dispatch:
    types: [run-ping-allinone, run-pong-allinone, run-done-allinone]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run ${{ github.event.client_payload.command }}
        run: npm run ${{ github.event.client_payload.command }} allinone
